# urls.py (add this to your URLs configuration)
from django.urls import path
from .views import *
urlpatterns = [
    path('login/', login, name='login'),
    path('get-user-geoids/', get_user_geoids_with_details, name='get_user_geoids'),
    path('', login_page, name='login_page'),
    path('products/', products, name='products'),
    path('products_page/', products_page, name='products_page'),
    path("asset_map/", asset_map_view, name="asset_map_page"),
    path("geoids/", get_geoids, name="api_geoids"),
    path("field-boundary/<str:geoid>/", get_field_boundary, name="api_field_boundary"),
    path('logout/', logout_view, name='logout_api'),
    path('delete-field/<str:field_id>/', delete_field, name='delete_field'),
    path('scope_map/', scope_map, name='scope_map'),
    path('get_user_scope/', get_user_scope, name='get_user_scope'),
    path('get_coordinates/<str:scope>/', get_coordinates, name='get_coordinates'),
    path("getScopesBB/", get_scopes_bb, name="get_scopes_bb"),
    path("request-activation/", request_activation, name="request_activation"),
    path("remove_scope/", remove_scope, name="remove_scope"),
    path("add_user_scope/", add_user_scope, name="add_user_scope"),
    path("fetch-field-bb/", fetch_field_bb, name="fetch_field_bb"),
    path("forgot_password_page/", forgot_password_page, name="forgot_password_page"),
    path("forgot_password", forgot_password, name="forgot_password"),
    path("register", signup_page, name="signup_page"),
    path("signup", signup, name="signup"),
    path('pricing/', pricing_page, name='pricing_page'),
    path('create-checkout-session/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('success/', payment_success, name='payment_success'),
    path('cancel/', payment_cancel, name='payment_cancel'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart_page'),
    path('cart/clear/', ClearCartView.as_view(), name='clear_cart'),
    path('cart/checkout/', CreateCartCheckoutSessionView.as_view(), name='create_cart_checkout_session'),
    path('cart-payment-success/', CartPaymentSuccessView.as_view(), name='cart_payment_success'),
    path('get_tile_number/', get_tile_number, name='get_tile_number'),
    path('get_eta_daily_data/', get_eta_daily_data, name='get_eta_daily_data'),
    path('getDailyETAStats/<str:geoid>/', eta_data_view, name='eta_data_view'),
    path('get_eta_weekly_data/', get_eta_weekly_data, name='get_eta_weekly_data'),
    path('getWeeklyETAStats/<str:geoid>/', eta_weekly_data_view, name='eta_weekly_data_view'),
    path('ndvi_dates/', ndvi_dates, name='ndvi_dates'),
    path('ndvi_dates_earlier/', ndvi_dates_earlier, name='ndvi_dates_earlier'),
    path('ndvi_image/', ndvi_image, name='ndvi_image'),
    path('getNDVIStats/<str:geoid>/', ndvi_image_view, name='ndvi_image_view'),
    path('get_data_apps/', get_data_apps, name='get_data_apps'),
    path('data_apps/', data_apps, name='data_apps'),


]
