# Generated by Django 4.2.23 on 2025-06-17 07:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('description', models.TextField()),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('dev_stage', models.CharField(max_length=50)),
                ('price_scope_month', models.FloatField(blank=True, null=True)),
                ('root', models.CharField(max_length=255, unique=True)),
                ('meta_data', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='UserApplicationAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('api_called', models.IntegerField(blank=True, null=True)),
                ('served_data_size', models.FloatField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Application Association',
                'verbose_name_plural': 'User Application Associations',
                'db_table': 'user_application_association',
                'unique_together': {('user', 'application')},
            },
        ),
    ]
