# Generated by Django 4.2.23 on 2025-06-13 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_registry_id', models.UUIDField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
