# Generated by Django 4.2.23 on 2025-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_user_user_registry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_registry_id',
            field=models.UUIDField(unique=True),
        ),
    ]
