# Generated by Django 4.2.23 on 2025-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20250618_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_registry_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
