# Generated by Django 4.2.23 on 2025-06-18 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_user_user_registry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_registry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
