# Generated by Django 4.2.23 on 2025-06-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_user_user_registry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplicationassociation',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='api_called',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='application',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.application'),
        ),
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='served_data_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
