# Generated by Django 4.2.23 on 2025-06-19 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userapplicationassociation_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='user_registry_id'),
        ),
    ]
