# Generated by Django 4.2.23 on 2025-06-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_userapplicationassociation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthorizationsaccess',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
