# Generated by Django 4.2.23 on 2025-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userauthorizationsaccess_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='S2CellToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cell_token', models.TextField(unique=True)),
            ],
            options={
                'db_table': 's2_cell_tokens',
            },
        ),
    ]
