# Generated by Django 4.2.23 on 2025-06-23 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_s2celltoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIDs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geo_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('geo_data', models.JSONField(blank=True, null=True)),
                ('authority_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('boundary_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'geo_ids',
                'managed': False,
            },
        ),
    ]
