# Generated by Django 4.2.23 on 2025-06-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_custom_meta_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
