# Generated by Django 4.2.23 on 2025-06-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user'),
        ('dashboard', '0014_alter_application_meta_data'),
    ]

    operations = [
    ]
