# Generated by Django 4.2.23 on 2025-06-23 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_geoids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsGeoID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cells_geo_ids',
                'managed': False,
            },
        ),
    ]
