# Generated by Django 4.2.23 on 2025-06-25 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_cellsgeoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s2celltoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
