# Generated by Django 4.2.23 on 2025-06-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_s2celltoken_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsGeosMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_links', to='dashboard.geoids')),
                ('s2celltoken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_links', to='dashboard.s2celltoken')),
            ],
        ),
    ]
